#!/bin/bash

docker run -d --restart=always --mount type=volume,source=hatchery,destination=/etc/mysql --env MYSQL_DATABASE="zerglings" --env MYSQL_ROOT_PASSWORD="Kerrigan" --name spawning-pool mysql
