#!/bin/bash

docker run --name Abathur -v $HOME:/root -dit -p 3000:3000 python:2-slim

docker exec Abathur pip install flask

echo 'from flask import Flask\napp=Flask(__name__)\n@app.route("/")\ndef hello():\n\treturn "<h1>Hello World !</h1>" ' > ~/main.py && chmod 777 ~/main.py

docker exec --env FLASK_APP=/root/main.py Abathur flask run --host=0.0.0.0 --port=3000
